jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZMK Firmware
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake gcc g++ python3-pip dtc
          python3 -m pip install --upgrade west
      - name: Initialize West
        run: west init -l .
      - name: Update West Modules
        run: west update
      - name: Build Firmware
        run: west build -d build -b nice_nano app -- -DSHIELD=24key_ble
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: 24key_ble_firmware
          path: build/zephyr/zmk.uf2