name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 取出 ZMK firmware
      - name: Checkout ZMK Firmware
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2️⃣ 安裝依賴
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake gcc g++ python3-pip dtc
          python3 -m pip install --upgrade west

      # 3️⃣ 初始化 west
      - name: Initialize West
        run: west init -l .
      
      - name: Update West Modules
        run: west update

      # 4️⃣ Build firmware
      - name: Build 24key BLE Firmware
        run: |
          west build -d build -b nice_nano app -- -DSHIELD=24key_ble
          
      # 5️⃣ 上傳 artifact（可選）
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: 24key_ble_firmware
          path: build/zephyr/zmk.uf2