name: Build 24key BLE Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 取得 firmware repo + submodules
      - name: Checkout Firmware
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2️⃣ 安裝編譯依賴
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake gcc g++ python3-pip dtc
          python3 -m pip install --upgrade west

      # 3️⃣ 初始化 West
      - name: Initialize West
        run: west init -l .
      
      - name: Update West Modules
        run: west update

      # 4️⃣ 列出 firmware 裡的 shields (確認 CMake 可以看到)
      - name: List Shields
        run: ls -R zmk-24key/app/shields

      # 5️⃣ Build Firmware
      - name: Build Firmware
        run: west build -d build -b nice_nano zmk-24key/app -- -DSHIELD=24key_ble

      # 6️⃣ 上傳編譯好的韌體
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: 24key_ble_firmware
          path: build/zephyr/zmk.uf2